# Generated by Django 5.2.8 on 2025-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
