# Generated by Django 5.2.8 on 2025-11-21 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_delete_userprofile'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='volunteer_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.campaign'),
        ),
    ]
