# Generated by Django 5.2.8 on 2025-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_volunteer_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='volunteer_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
